_prefs: 
  baselayer: ''
  mapid: trilliumtransit.7c0460cb
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85
  - 180
  - 85
center: 
  - -123.0527
  - 39.0696
  - 11
description: ''
format: "png8:m=h:c=64"
interactivity_layer: ''
layers: 
  - landuse
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - route-4
  - route-1
  - route-3
  - rt7-to-mendo-college
  - rt-7-to-mendo-airport
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - key-connections
maxzoom: 19
minzoom: 0
name: Lake 5311(f) application
source: "mapbox:///mapbox.mapbox-streets-v5,trilliumtransit.1985c30e"
styles: 
  - vars.mss
  - bg.mss
  - road.mss
  - transit_routes.mss
  - label.mss
  - poi_classic.mss
template: ''
